services:
  postgres:
    image: postgres:16-alpine
    container_name: minor-project-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: internships
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d internships"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: minor-project-backend
    environment:
      APP_PORT: 5051
      SEED_DB: "1"
      DATABASE_URL: postgresql+psycopg2://app:app@postgres:5432/internships
    ports:
      - "5051:5051"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: minor-project-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
  backend_uploads:
